version: '3'
services:
  cloudflared-web:
    image: wisdomsky/cloudflared-web:latest
    container_name: cloudflared-web
    restart: unless-stopped
    environment:
      - WEBUI_PORT=${WEBUI_PORT:-14333}
      - EDGE_IP_VERSION=${EDGE_IP_VERSION:-auto}
      - PROTOCOL=${PROTOCOL:-auto}
      - METRICS_ENABLE=${METRICS_ENABLE:-false}
      - METRICS_PORT=${METRICS_PORT:-60123}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER:-admin}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
    volumes:
      - ${DATA_DIR:-/var/lib/nestos/plugins/cloudflared-web}/config:/config
    ports:
      - "${WEBUI_PORT:-14333}:${WEBUI_PORT:-14333}"
      - "${METRICS_PORT:-60123}:${METRICS_PORT:-60123}"
    networks:
      - nestos

networks:
  nestos:
    external: true